# Generated by Django 4.2.23 on 2025-08-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_updated_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="updated_on",
        ),
    ]
